# Fill in your handles to show a "Sponsor" button on the GitHub repo.
# Docs: https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: antonkarliner
# buy_me_a_coffee: your-bmc-username
# custom:
#   - https://www.timer.coffee
